vmware/cluster-api-provider-cloud-director

- config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachinetemplates.yaml
- controllers/cluster_scripts/cloud_init_control_plane.yaml
- controllers/cluster_scripts/cloud_init_node.yaml
- controllers/vcdcluster_controller.go
- controllers/vcdmachine_controller.go
- go.mod
- pkg/vcdclient/auth.go
- pkg/vcdclient/vm_extra_config.go
- pkg/vcdclient/vm_types.go
- pkg/vcdclient/vms.go
- pkg/vcdclient/vms_test.go
- testdata/config_test.yaml
- vendor/modules.txt
working extra config, testing cluster creation
Cloudinit debugging
Use go embed for cluster scripts
Copied vcdswaggerclient from CPI
added vm phase logging
Make CPI, CSI work
using public url for public repo and restored common_system_test
removed logging config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/6)
> [VCDA-3048] read and write operations for vm extra config

- controllers/vcdmachine_controller.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/9)
> logging for phase success and error

- config/rbac/role.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/15)
> Add rights for kubeadmconfigtemplate verbs

- controllers/vcdcluster_controller.go
Rename capvcd entity type's schema to match changes in CSE
@sahithi @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/5)
> Change capvcd cluster schema

- controllers/vcdcluster_controller.go
- controllers/vcdmachine_controller.go
- pkg/vcdclient/client.go
- pkg/vcdclient/defined_entity.go
- pkg/vcdclient/gateway.go
- pkg/vcdclient/vms.go
- Added verbosity level to all the logs (including client files)
- Added a check to skip the logic of waiting on script execution phases on every reconcile operation (even after the previous script execution failure)
- Ensured delete cluster goes through even if any of the VCD resources do not exist anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/20)
> Log refinement and some minor code fixes

- controllers/vcdmachine_controller.go
- pkg/config/cloudconfig.go
- pkg/vcdclient/gateway.go
Also some small changes to fix up secrets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/21)
> VCDA-3187: wait for VirtualService to be created properly.

- pkg/config/cloudconfig.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/24)
> [VCDA-3202] fix using default cloud config values

- controllers/errors.go
- controllers/vcdcluster_controller.go
- controllers/vcdmachine_controller.go
- pkg/vcdclient/gateway.go
Also cleanup some logging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/28)
> VCDA-3208: Patch the vcdCluster.Status.InfraId

- pkg/config/cloudconfig.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/29)
> [VCDA-3177] updated csi/cpi default versions

- pkg/vcdclient/vapp.go
* During reconciliation, try adding ovdc network to the vapp if vapp doesn't have an ovdc network present.
Testing:
create a cluster and make sure network gets added even when addition of network failed initially.
@arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/31)
> [VCDA-3217] Update network config section if ovdc network is not present in the Vapp

- scripts/README.md
- scripts/get-capvcd-logs.sh
Signed-off-by: Andrew Ni <niandrew7@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/30)
> Add log collection script

- config/manager/manager.yaml
Increase resource limits for CAPVCD pods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/35)
> Increase resource and limit for capvcd pods

- open_source_license.txt
Add OSL for CAPVCD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/33)
> [VCDA-2965]Add OSL for CAPVCD

- config/manager/manager.yaml
- release/version
Change version of CAPVCD to `main-branch`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/38)
> Change CAPVCD version to main-branch

- examples/capi-quickstart.yaml
- Added descriptive comments for the example input for CAPVCD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/39)
> [VCDA-3260] Add descriptive comments to the example capi-yaml input

- examples/capi-quickstart.yaml
Update tags in example/capi-quickstart.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/42)
> Update tags to use + and _ instead of -

- Makefile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/43)
> remove unnecessary touch command from Makefile

- examples/capi-quickstart.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/44)
> Change names in capi-quickstart objects

- controllers/cluster_scripts/cloud_init_control_plane.yaml
- controllers/cluster_scripts/cloud_init_node.yaml
TODO: testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/40)
> [VCDA-3254] checking for bootstrap success and logging cloud init output

- controllers/cluster_scripts/cloud_init_control_plane.yaml
- controllers/cluster_scripts/cloud_init_node.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/51)
> False positive

- docs/WORKLOAD_CLUSTER.md
This fix mainly addresses the following situation:
For the script on this page for getting the etcd and coredns versions,
the line last=$(echo ${K8S_VERSION} | rev | cut -f1 -d".") 
should be last=$(echo ${K8S_VERSION//*.})
With the current code, if the tkg version in tkg.X is tkg.10, then last  will evaluate to 01. The fix will make sure that X is 10. (The script is meant to stop when X > 10, so we would need this fix)
There are additional small fixes/edits in the script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/52)
> updated extract script for workload clusters

- docs/WORKLOAD_CLUSTER.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/55)
> [VCDA-3314] updated workload extract script (#52)

- controllers/cluster_scripts/cloud_init_control_plane.yaml
- controllers/cluster_scripts/cloud_init_node.yaml
* Reboot nodes if files written during `write_files` are not present on the machine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/53)
> [VCDA-3290] Restart nodes in cloud-init if files are absent

- controllers/cluster_scripts/cloud_init_control_plane.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/61)
> bug fix for antrea tkr image

- provenance.sh
Script needs to be executed  with the following format
`provenance.sh cluster-api-provider-cloud-director 0.5.x`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/69)
> Add provenance generation script file

- controllers/cluster_scripts/cloud_init_control_plane.yaml
Fixes VCDA-3416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/73)
> Use "" instead of '' so that environment variables are expanded

- controllers/cluster_scripts/cloud_init_control_plane.yaml
Fixes VCDA-3416. Could not be cherry-picked due to conflicts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/75)
> Fix sed script for antrea

- pkg/vcdclient/client.go
Fixes VCDA-3478
Earlier a cached copy was returned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/80)
> Always get a new client to ensure that clients are long-lived

- infrastructure-vcd/v0.8.0/metadata.yaml
* Metadata.yaml releaseSeries should also include past versions of CAPVCD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/90)
> Update metadata.yaml to include 0.5.0 release series

- config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachinetemplates.yaml
- infrastructure-vcd/v0.8.0/infrastructure-components.yaml
* Add v1beta1 CRDs to infrastructure components yaml
* Fix failing CAPVCD vm creation using infrastructure components.yaml
* 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/93)
> Add v1beta1 CRDs to infrastructure components yaml

- examples/capi-quickstart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/121)
> update example capi yaml to include storage profile

- Makefile
- README.md
- config/crd/kustomization.yaml
- docs/MANAGEMENT_CLUSTER.md
- examples/capi-quickstart.yaml
This one adds the kustomization.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/124)
> VCDA-3626: Add some pending code left out from v1beta1 change

- controllers/vcdcluster_controller.go
- controllers/vcdmachine_controller.go
- pkg/vcdclient/defined_entity.go
- pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go
ticket: VCDA-3516
* Example capvcd entitty status:
```
"status": {
"capvcd": {
"uid": "urn:vcloud:entity:vmware:capvcdCluster:7c7b03a0-8176-4004-b0c8-06e90bcf1522",
"phase": "Provisioned",
"private": {
"kubeConfig": "apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EUXhNVEl5TVRZd01Wb1hEVE15TURRd09ESXlNakV3TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT29JCkpDeXpwS25sYklmN2MvOXZqblI4TWdDS2tPQWtXNFlMNUxhRUlUcmtYNFBmM3dWd0RoY3JZWjFMTTVGN1ZVQk8KRCt2TGR3dVdRV3hxUFp3clRRNEZubDhGNkw4RS9xVmdZTE5yOHdEQm9kRCs0bWlLbDg5cDF0TkVmSFJCZTRaSgoyaERGdzZ3YmViZGxVZnhRTkl0UFdPakMzZFpoUnhG …
```
> Make changes to CAPVCD status as per the new schema

- controllers/vcdmachine_controller.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/132)
> remove TKR customization status

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/136)
> VCDA-3498: README changes for 0.5.1

- config/manager/manager.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/137)
> Manifest changes to point to projects.registry.vmware.com repo

- examples/capi-quickstart.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/129)
> Update example capi yaml to include useAsManagementCluster, parentUid

- Dockerfile
- Makefile
Had missed the Dockerfile update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/139)
> VCDA-3626: Also update go compiler in Dockerfile

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/141)
> [VSRC-11364] Remove build-with-docker which was not being used

- controllers/vcdcluster_controller.go
- controllers/vcdmachine_controller.go
- go.mod
- go.sum
- pkg/capisdk/capi_gateway_manager.go
- pkg/capisdk/defined_entity.go
- pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go
- release/release.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
* add and remove loadbalancer components, vapp and VM details to VCDResourceSet in RDE.
Testing done:
* Create a cluster
* check if all the resources are getting added to VCDResourceSet
* Add / remove a node
* Check if the created / delete node is added to / removed from VCDResourceSet
* Delete cluster
* check if all the loadbalancer components get removed from VCDResourceSet before RDE is deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/147)
> [VCDA-3467] Add LoadBalancer components, Vapp and VMs to VCDResourceSet

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/ipam.go
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/156)
> VCDA-3758: Update common-core

- controllers/vcdcluster_controller.go
- controllers/vcdmachine_controller.go
- go.mod
- go.sum
- pkg/capisdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/util/allocatedresources.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/util/set.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity_util.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/ipam.go
- vendor/modules.txt
Error and event reporting to RDE.
This does not cover all possible errors and events I mentioned in the confluence document. Please see the list of <event, error> pairs this PR has here - https://confluence.eng.vmware.com/display/VCD/CAPVCD+Errors+and+Events
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/166)
>  [VCDA-3468] Error and event reporting to RDE.status.capvcd

- controllers/vcdcluster_controller.go
We need to set the vcdCluster.status.RdeVersionInUse to the correct value for new cluster creations with precreated RDEs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/175)
> [VCDA-3866 ] Fixing the bug for the cluster creation - RDE upgrade failure

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/179)
> VCDA-3741 update cpi dependency

- controllers/vcdmachine_controller.go
- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
LEAST_CONNECTIONS affects multi-control-plane cluster creation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/181)
> VCDA-3880: use ROUND_ROBIN in capvcd cluster creation since

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/183)
> VCDA-3816 Update CPI dependency

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/185)
> update cpi dependency to fix auth bug with tokens

- provenance_v2.sh
- New provenace data generation script which uses srp cli
Are there API changes? - NA
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/194)
> Add provenance data generation and upload script using srp cli

- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- Hardcode `vkp` for CSI and CPI version in infrastructure-components.yaml
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/193)
> [VCDA-3971] Use 'vkp' branch of CPI and CSI in CAPVCD infrastructure yaml to allow for Beta testing

- controllers/capi_objects_utils.go
- controllers/vcdcluster_controller.go
- main.go
- pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go
- schema/schema_1_1_0.json
- vendor/modules.txt
Iterate through ClusterResourceSetBindings and update RDE. Also remove CNI hardcoded
- 
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/195)
> VCDA-3582, 3740: Store CRS in RDE, remove CNI

- Makefile
- api/v1beta1/vcdcluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml
- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- Fixed some things missing in earlier merge request. Also fixed build of `kustomize`
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/198)
> Fixes missing in the merge

- controllers/cluster_scripts/cloud_init.tmpl
- 
- [] updated any relevant dependencies
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/202)
> VCDA-4023: add cloud-init reboot mitigation

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/NOTICE.txt
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
- Update common core changes to handle vApp busy network issue
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/204)
> [VCDA-4029] Update CPI common core dependencies from July 11

- controllers/vcdcluster_controller.go
- 
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/206)
> VCDA-3751: since CPI and CSI are tagged, point to the tags

- schema/schema_1_1_0.json
- 
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/214)
> VCDA-4137 update rde schema with default storage class options

- config/manager/manager.yaml
- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- Remove unused volume mount from CAPVCD deployment
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/219)
> remove unused volume mount from CAPVCD deployment

- schema/schema_1_1_0.json
- Minor bug that prevented the RDE to be fully resolved
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/224)
> [Bugfix] useDeleteReclaimPolicy fix for schema

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/auth.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
-  update latest CPI in vendor folder
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/230)
> [VCDA-4212] update latest CPI in vendor folder

- controllers/cluster_scripts/cloud_init.tmpl
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/231)
> Fix panic caused by directive

- controllers/cluster_scripts/cloud_init.tmpl
- controllers/vcdmachine_controller.go
- docs/MANAGEMENT_CLUSTER.md
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/236)
> VCDA-3666 small updates to cloud init and docs

- docs/MANAGEMENT_CLUSTER.md
- Fix indentations in the Docs for CPI and CSI CRS files
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/232)
> indentation fix for the csi and cpi docs

- scripts/README.md
- Add troubleshooting docs for wire logging
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/237)
> Docs for wire logging

- tanzu/crs/v.1.4.3/v1.4.3-antrea.yaml.template
- tanzu/crs/v.1.4.3/v1.4.3.yaml.template
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/244)
> [VCDA-4353] add tanzu crs file for v1.4.3

- controllers/cluster_scripts/cloud_init.tmpl
- controllers/vcdmachine_controller.go
- Update cloud init script with correct nvidia configuration
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/247)
> VCDA-3666 update nvidia sections in cloud-init

- config/manager/manager.yaml
- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- Update image tags for testing
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/257)
> update image tags after rde upgrade section changes

- controllers/vcdmachine_controller.go
- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
Signed-off-by: rliang88 <rliang@vmware.com>
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/259)
> [VCDA-4391] updated CPI vendor package and updated call to AddNewVM()

- config/manager/manager.yaml
- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/262)
> Update image tag with latest CAPVCD changes

- schema/schema_1_1_0.json
- Update node pool section in the schema to proper format
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/268)
> [VCDA-4459] Fix node pool section in schema.json 

- config/manager/manager.yaml
- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- Update image tags for changes made to CAPVCD
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/267)
> Update image tags

- config/manager/manager.yaml
- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- Just a rebuild with a new registry location 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/269)
> VCDA-4463: Release FC for CAPVCD

- config/manager/manager.yaml
- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- Update to internal harbor with latest code change commit
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/277)
> [VCDA-4509] Update imagetag to commit df8d098

- main.go
- Sync time needs to change to 10 minutes to avoid frequent recinciliations
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/276)
> [VCDA-4530]Change sync time to 10 minutes

- README.md
- Update stale README
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/274)
> [VCDA-4377] Update README in main to include 0.5.1 release

- controllers/vcdmachine_controller.go
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/279)
> [VCDA-4534] Fix HTTPProxy not being populated 

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/modules.txt
- Update common core used in CAPVCD to pull in changes for limiting RDE updates to VCD resource set
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/281)
> [VCDA-4565] Update common core used in CAPVCD

- controllers/vcdcluster_controller.go
- go.mod
- go.sum
- pkg/capisdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/ipam.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_certificate_library_modified.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_defined_entity.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_load_balancer_pool.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_load_balancer_pools.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_load_balancer_virtual_service.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_load_balancer_virtual_services_modified.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_nat_rule.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_edge_gateway_nat_rules.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_load_balancer_service_engine_group_assignments.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_org_vdc_network.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_org_vdc_networks.go
- vendor/modules.txt
- Update cloud api calls in CAPVCD to send tenant org context.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/286)
> [VCDA-4596]Update CPI common core and update cloud api calls

- config/manager/manager.yaml
- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/287)
> [VCDA-4616] Update image tag to the latest main from 10/7

- release/version
- Change version to point to 1.0.z
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/288)
> VCDA-4599: Cut branch for 1.0.z

- config/manager/manager.yaml
- infrastructure-vcd/v1.0.0/infrastructure-components.yaml
- Make and push from latest code
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/290)
> VCDA-4223: Build images and point to them

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_certificate_library_modified.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/vcdconstants.go
- vendor/modules.txt
- Update CPI common core using the CPI commit b8bdde7 (from CPI 1.2.z) 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/294)
> [VCDA-4635] Update CPI common core in CAPVCD 1.0.z using commit b8bdde7 (CPI v1.2.z branch)

- config/manager/manager.yaml
- templates/infrastructure-components.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/301)
> [VCDA-4666] Refresh CAPVCD image to latest commit from common core refresh - 6077656

- controllers/vcdcluster_controller.go
- Fix unhandled error when loadbalancer creation fails
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/312)
> [VCDA-4717] Handle error when load balancer creation fails

- controllers/vcdcluster_controller.go
- update function to validate derived properties to check RDE version in status only if it is empty
Fixes https://github.com/vmware/cluster-api-provider-cloud-director/issues/309
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/315)
> [VCDA-4713] Fix cluster creation with CAPVCD_SKIP_RDE set to true (#313)

- config/manager/manager.yaml
- templates/infrastructure-components.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/318)
> [VCDA-4729] Refresh CAPVCD 1.0.z image to commit 4841b3c

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/auth.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/defined_entity.go
- vendor/modules.txt
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/321)
> [VCDA-4746] Consume common core from CPI 1.2.z commit ee1c9e6

- config/manager/manager.yaml
- templates/infrastructure-components.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/322)
> [VCDA-4750] Refresh CAPVCD 1.0.z image up to commit bee3e77

- open_source_license.txt
- Update OSL for CAPVCD 1.0.0 GA
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/326)
> [VCDA-3806] Change open source license for 1.0.0 GA

- open_source_license.txt
- Update OSL for 1.0.0 GA
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/328)
> [VCDA-3806] Change open source licence for 1.0.0 GA (#326)

- docs/MANAGEMENT_CLUSTER.md
- Some kubectl commands needed some correction.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/329)
> [VCDA-4773] Update kubectl commands to create secrets and configmaps in MANAGEMENT_CLUSTER.md

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
- Refresh common-core in CAPVCD with commit fc36ada
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/333)
> [VCDA-4760] Refresh common-core in CAPVCD (commit fc36ada from CPI 1.2.z)

- controllers/vcdmachine_controller.go
- the code to redact the cloud init file is not necessary anymore.
- Redaction was needed when the cloud init script had authentication information for CPI and CSI.
- currently capvcd uses CRS to install CPI and CSI and they are installed separately
- So, Redacting the cloud init script is not needed
Fixes #
- - - …
> [VCDA-4757] Remove code to redact the cloud init script as redaction logic is not necessary anymore (#335)

- config/manager/manager.yaml
- templates/crs/cpi/cloud-director-ccm.yaml
- templates/crs/csi/csi-controller-crs.yaml
- templates/crs/csi/csi-node-crs.yaml
- templates/infrastructure-components.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/346)
> [VCDA-4808], [VCDA-4811] - Update CAPVCD main image to commit 6409b2b, update CRS manifest image tags

- README.md
- docs/CLUSTERCTL.md
- docs/CRS.md
- docs/MANAGEMENT_CLUSTER.md
- docs/MULTITENANCY.md
- docs/UPGRADES.md
- docs/VCD_SETUP.md
- docs/WIRE_LOGS.md
- docs/WORKLOAD_CLUSTER.md
- templates/clusterctl.yaml
CAPVCD 1.0.0 documentation
- Added new pages for clusterctl, crs, multitenancy
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/347)
> [VCDA-4818] CAPVCD 1.0.0 documentation

- README.md
- docs/CLUSTERCTL.md
- docs/CRS.md
- docs/MANAGEMENT_CLUSTER.md
- docs/MULTITENANCY.md
- docs/UPGRADES.md
- docs/VCD_SETUP.md
- docs/WIRE_LOGS.md
- docs/WORKLOAD_CLUSTER.md
- templates/clusterctl.yaml
CAPVCD documentation updates
(cherry picked from commit d770e84e0176c9f91d4436de44b03d76384a44ef)
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/351)
> [VCDA-4818] CAPVCD 1.0.0 documentation (#347)

- docs/CLUSTERCTL.md
- docs/CRS.md
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/352)
> Changed the references in the documentation to 1.0.0 directories

- config/manager/manager.yaml
- config/manager/manager.yaml.template
- templates/crs/cpi/cloud-director-ccm.yaml
- templates/crs/csi/csi-controller-crs.yaml
- templates/crs/csi/csi-node-crs.yaml
- templates/infrastructure-components.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/353)
> Changed the registry to public repo for 1.0.z

- controllers/vcdmachine_controller.go
When we call vm.UpdateNetworkConnectionSection method, we update network interfaces of the VM. Then we call getPrimaryNetwork function but it uses old vm object. We need to update vm object after updating network configuration for consistency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/368)
> Update vm.VM object after updating network configuration

- docs/CRS.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/376)
> Update CRS.md - use workload cluster name

- controllers/vcdmachine_controller.go
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
Tested running cluster creation in TKG 1.6.1 and 1.5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/382)
> [CAFV-161] Call TKG VM creation function

- README.md
- Reverse the order of tables described in README.md
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/385)
> [CAFV-142] Reverse order of the tables in README.md

- README.md
- Update readme tables to have latest version at the top
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/387)
> [CAFV-142] Update README.md to have latest version at the top

- templates/crs/tanzu/v1.6.1/v1.6.1-antrea.yaml.template
- templates/crs/tanzu/v1.6.1/v1.6.1.yaml.template
Deployed cluster through VCD-KE and saw core packages came up using tanzu-cli. I cross-referenced the packages with the tanzu crs files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/388)
> [CAFV-92] tkg 1.6.1 tanzu crs files

- templates/cluster-template-v1.23.10-crs.yaml
- templates/cluster-template-v1.23.10.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/390)
> [CAFV-93 & CAFV-94] TKG 1.6.1 k8s 1.23 cluster & crs templates

- .gitlab-ci.yml
- Makefile
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/389)
> [VCDA-4852] Add build file to push image to registry

- Makefile
- config/manager/manager.yaml.template
- Updates tagging for containers
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/401)
> [CAFV-176] Update tagging manifests with version-gitcommit

- docs/WORKLOAD_CLUSTER.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/404)
> outputting etcd and coredns versions in docs script

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
a
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/416)
> [CAFV-193][common-core] sync with safe ovdc name access

- Dockerfile
- Makefile
- artifacts/bom.json.template
- artifacts/dependencies.txt.template
- config/manager/manager.yaml.template
Currently the capvcd dev images are tagged with release/version-gitsha and prod images are tagged with release/version string. However the version string stored in the binary is alway release/version.
In this PR, we have cleaned up the Makefile and Dockerfile to ensure that proper version strings are set on the binary too.
make dev
make prod
- 
- [X ] tested locally
- [X ] No
- [X ] No
- [ X] No
- [ X] No
- [X ] No
- [ X] No
Fixes #
- - - …
> Cleanup Makefile and DockerFile to use release/version for prod builds and release/version-gitsha for dev builds

- artifacts/bom.json.template
- artifacts/dependencies.txt.template
- config/manager/manager.yaml.template
- Cherrypicked from main branch (commit f663e4d)
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/423)
> [CAFV-200] Cherrypick – Update generated manifests to point to projects.registry.vmware.com

- templates/infrastructure-components.yaml
- Update image in infrastructure-components.yaml
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/425)
> [CAFV-212] Update to latest capvcd image in infrastructure-components.yaml

- templates/infrastructure-components.yaml
…sting
- Updates the CAPVCD image to latest dev version (1.0.1)
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/431)
> [CAFV-218] – Update CAPVCD image to internal harbor with 1.0.1 for testing

- docs/CLUSTERCTL.md
- docs/CRS.md
- docs/UPGRADES.md
-  Update upgrade process in CAPVCD 1.1.0 documentation
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/426)
> [CAFV-211] Update upgrade process in CAPVCD 1.1.0 documentation

- scripts/get-capvcd-logs.sh
- Update log collection script to take kubeconfig as a parameter
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/461)
> [CAFV-278] update log collection script to take kubeconfig as a parameter

- open_source_license.txt
- update OSL file for CAPVCD 1.1.0
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/470)
> [CAFV-289] update OSL file for CAPVCD 1.1.0

- open_source_license.txt
(cherry picked from commit https://github.com/vmware/cluster-api-provider-cloud-director/commit/9427aa74d4954fb2c7a6a8cd864e621a67f3b524)
- Update CAPVCD 1.1.0 GA OSL file
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/471)
> [Cherry-pick][CAFV-289]Update CAPVCD 1.1.0 GA OSL file

- templates/cluster-template-v1.24.10-crs.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/477)
> [CAFV-290] catch up missing content on the v1.24 yaml file

- README.md
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/479)
> [CAFV-291][Docs]Upgrade story around TKG versions

- templates/crs/cpi/cloud-director-ccm.yaml
- templates/crs/csi/csi-controller-crs.yaml
- templates/crs/csi/csi-node-crs.yaml
- update CSI and CPI CRS files
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/482)
> [CAFV-214] update CSI and CPI CRS files

- templates/crs/cpi/cloud-director-ccm.yaml
- templates/crs/csi/csi-controller-crs.yaml
- templates/crs/csi/csi-node-crs.yaml
(cherry picked from commit b7a23ceb102eabc8ace028a7f3fe640ccfbc7614)
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/492)
> [Cherry-pick][CAFV-214] update CSI and CPI CRS files (#482)

- config/manager/manager.yaml
- templates/infrastructure-components.yaml
- Update image tag to public harbor v1.1.0
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/493)
> [CAFV-300] Update image tags to public harbor v1.1.0

- templates/clusterctl.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/495)
> Updated clusterctl.yaml in the template folder to reflect newer versions

- docs/CLUSTERCTL.md
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/498)
> Update clusterctl docs for 1.1.0 branch

- docs/CLUSTERCTL.md
Update clusterctl docs for main branch
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/497)
> Update clusterctl docs for main branch

- config/manager/manager.yaml
- templates/infrastructure-components.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/494)
> [Cherry-pick][CAFV-300] Update image tags to public harbor v1.1.0 (#493)

- go.mod
- go.sum
- vendor/github.com/sethvargo/go-password/LICENSE
- vendor/github.com/sethvargo/go-password/password/generate.go
- vendor/github.com/sethvargo/go-password/password/mock.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
- update common core to get the changes for creating 15 char passwords for cluster node VMs
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/508)
> [CAFV-310] Sync common core for the ability to create VMs with 15 char password

- Dockerfile-ConversionGen
- Makefile
- go.mod
- upgrade go version to 1.20.7
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/509)
> [CAFV-312] CAPVCD upgrade go version to 1.20.7

- go.mod
- go.sum
- vendor/github.com/cespare/xxhash/v2/README.md
- vendor/github.com/cespare/xxhash/v2/testall.sh
- vendor/github.com/cespare/xxhash/v2/xxhash.go
- vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
- vendor/github.com/cespare/xxhash/v2/xxhash_arm64.s
- vendor/github.com/cespare/xxhash/v2/xxhash_asm.go
- vendor/github.com/cespare/xxhash/v2/xxhash_other.go
- vendor/github.com/cespare/xxhash/v2/xxhash_safe.go
- vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
- vendor/github.com/sethvargo/go-password/LICENSE
- vendor/github.com/sethvargo/go-password/password/generate.go
- vendor/github.com/sethvargo/go-password/password/mock.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/modules.txt
- Update common core to point to latest CPI 1.4.z
Fixes #CAFV-321
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/510)
> CAFV-321: Point to common-core of latest CPI 1.4.z

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
- vendor/modules.txt
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/517)
> [CAFV-322] common-core-sync from cpi main commit e68e5d199d99

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
- vendor/modules.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/518)
> [CAFV-322] common core sync from cpi 1.4.z commit 8134f65

- artifacts/bom.json.template
- artifacts/dependencies.txt.template
…, bom.json.template (#520)
(cherry picked from commit 8cf2b46657a8d7a5747a147ef740aeb54e37d5e2)
- Cherry-picked commit 8cf2b46657a8d7a5747a147ef740aeb54e37d5e2 from main
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-direct …
> [CAFV-325] Use placeholders for registry in dependencies.txt.template, bom.json.template

- config/manager/manager.yaml
- templates/infrastructure-components.yaml
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/528)
> [CAFV-331] update manifests for release

- go.mod
- go.sum
- vendor/modules.txt
- update CPI common core to the latest CPI commit in main branch
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/533)
> [CAFV-343] update CPI common core to the latest CPI commit in main branch

- Makefile
The targets that depend on bin/ and bin/testbin write files to them, giving them newer timestamps than the targets themselves, and causing make to always remake the targets.
- -
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/515)
> build: Do not use bin/ and bin/testbin as make dependencies

- controllers/cluster_scripts/cloud_init.tmpl
- enable ssh password based login for root user using cloud init
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/535)
> [CAFV-307] changes to cloud init to enable ssh password based login for root user

- metadata.yaml
Update capvcd metadata.yaml with new version 1.2.0
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/544)
> Update capvcd metadata.yaml with new version 1.2.0

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
- Update CAPVCD common core with CPI release branch commit 203ccc9
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/553)
> [CAFV-381] Update CAPVCD common core with CPI release branch commit 203ccc9

- open_source_license.txt
Update OSL for CAPVCD 1.2.0 GA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/571)
> [CAFV-396] Update OSL for CAPVCD 1.2.0 GA 

- open_source_license.txt
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com>
(cherry picked from commit 94c0bfde359b70af971da91c04f43c526a991303)
- Update GA OSL on github for CAPVCD 1.2.0 GA release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/572)
> [CAFV-396] Update OSL for CAPVCD 1.2.0 GA

- Makefile
- Remove registry substitutions and references, and hardcode to push to projects-stg
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/579)
> [VCDA-6925] Remove registry references in Makefile

- Makefile
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/589)
> [VCDA-6931] Consolidate makefile with appropriate gobuild targets

- controllers/vcdcluster_controller.go
- go.mod
- go.sum
- pkg/capisdk/capi_gateway_manager.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
Refresh common core from CPI main branch.
Update gateway code to consume IP space related changes in common core. (commit : ba3f23650c61ba2176a57bd8ff0688bb3a68d79d)
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/602)
> [x-port] [CAFV-443] Consume latest common-core from CPI 1.6.0 to enable IP space support (#599)

- api/v1beta3/vcdcluster_webhook.go
- controllers/vcdcluster_controller.go
- Add validation webhook to prevent changes to vcdCluster.spec.controlPlaneEndpoint field
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/600)
> [CAFV-432] add validation webhook to prevent control plane endpoint change

- templates/cluster-template-v1.26.11-tkgv2.5.0-crs.yaml
- templates/cluster-template-v1.26.11-tkgv2.5.0.yaml
- templates/cluster-template-v1.27.8-tkgv2.5.0-crs.yaml
- templates/cluster-template-v1.27.8-tkgv2.5.0.yaml
- templates/cluster-template-v1.28.4-tkgv2.5.0-crs.yaml
- templates/cluster-template-v1.28.4-tkgv2.5.0.yaml
* tkg 2.5.0 placeholder files
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com>
* updated coredns, etc and k8 versions
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com>
* update the component versions in the comment to match the actuals
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com>
---------
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com>
(cherry picked from commit a975aee461232e72a9c457fe37b0a95cfece7081)
- 
- [ X] No
If applicable, …
> [CAFV-448] tkg templates for clusterctl cherry-pick

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
- CPI common core update. Fixes issue when DC group network is used for cluster creation
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/611)
> [CAFV-452][common core sync] for fixes to get the edge gw for a dc group nw

- api/v1alpha4/vcdcluster_conversion.go
- api/v1beta1/conversion.go
- api/v1beta1/vcdcluster_conversion.go
- api/v1beta1/zz_generated.conversion.go
- api/v1beta2/vcdcluster_conversion.go
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/613)
> [CAFV-440] fix conversion errors

- go.mod
- go.sum
- vendor/github.com/golang/protobuf/ptypes/any.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/org.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/zonemap.go
- vendor/modules.txt
- sync the latest CPI code
- Upgrade protobuf to 1.5.4
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/618)
> [CAFV-457] sync the latest CPI code AND update protobuf

- docs/CLUSTERCTL.md
- updated main core capi version to v1.5.4
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/616)
> [CAFV-449][1.1.z] update CLUSTERCTL.md with updated versions

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
- sync the latest CPI common code - 0c0403c006c50df75d8773f7261a8ee12a0e25c9
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/619)
> [CAFV-458] sync the latest CPI common code - 0c0403c006c50df75d8773f7261a8ee12a0e25c9

- docs/CLUSTERCTL.md
- title
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/622)
> [CAFV-460][1.1.z]update CLUSTERCTL.md with TKG catalog management table

- docs/CLUSTERCTL.md
- title
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/623)
> [CAFV-460][1.2.z]update CLUSTERCTL.md with TKG catalog management table

- docs/CLUSTERCTL.md
- title
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/624)
> [CAFV-460][1.3.z]update CLUSTERCTL.md with TKG catalog management table

- controllers/vcdcluster_controller.go
- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
- vendor/modules.txt
- There were a few places where VDC was used from spec.ovdc which was an incorrect flow. 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/626)
> CAFV-436: allow single-zone cluster creation

- controllers/vcdcluster_controller.go
- Fixes a null pointer exception
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/634)
> [CAFV-471] fix null pointer exception while populating VDC for client

- docs/CLUSTERCTL.md
- docs/CRS.md
- update CLUSTERCTL.md with relevant CRS versions
- CRS.md examples tell users they can use custom path 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/632)
> [CAFV-466][1.2.z] Bring CLUSTERCTL.md and CRS.md up to date

- docs/CLUSTERCTL.md
- docs/CRS.md
- use relevant CRS version in CLUSTERCTL.md
- examples in CRS.md tell users they can use custom path
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/631)
> [CAFV-466][1.1.z] bring CLUSTERCTL.md and CRS.md up-to-date

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/capiyaml_utils.go
- vendor/modules.txt
- [CAFV-482] sync the latest CPI common code - 6dd634a
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/645)
> [CAFV-482] sync the latest CPI common code - 6dd634a

- go.mod
- go.sum
- vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient_37_2/api_defined_entity_modified.go
- vendor/modules.txt
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/657)
> Consume common core that can log update defined entity calls
