vmware/cluster-api-provider-cloud-director

schema/schema_1_0_0.json

Updates status.network, status.parentUid, status.IsManagementCluster (I removed status.cni). Also note that spec.topology.workers and spec.topology.controlplane have become arrays.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/7)

Updated capvcd schema_1_0_0.json

---

config/rbac/role.yaml

Testing Done:
- checked if there is no forbidden error while listing mds, vcdmachinetemplates and kcps.
@sahithi @arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/12)

[VCDA-3164]Add rights to verbs for machinedeployments, vcdmachinetemplate and kcps

---

controllers/capi_objects_utils.go
controllers/convert_objects.go
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
main.go
pkg/vcdtypes/types.go
schema/schema_1_0_0.json

Defined entity: 
```
{
"id": "urn:vcloud:entity:vmware:capvcd:02387512-9b48-46f3-b72b-11ba8172e016",
"entityType": "urn:vcloud:type:vmware:capvcd:1.0.0",
"name": "capi-cluster",
"externalId": null,
"entity": {
"kind": "CAPVCDCluster",
"spec": {
"capiYaml": "apiversion: cluster.x-k8s.io/v1alpha4\nkind: Cluster\nmetadata:\n  name: capi-cluster\n  namespace: default\nspec:\n  clusternetwork:\n    apiserverport: null\n    pods:\n      cidrblocks:\n      - 192.168.0.0/16\n    servicedomain: k8s.test\n    services:\n      cidrblocks:\n      - 10.96.0.0/12\n  controlplaneendpoint:\n    host: 10.150.161.96\n    port: 6443\n  controlplaneref:\n    apiversion: controlplane.cluster.x-k8s.io/v1alpha4\n    fieldpath: \"\"\n    kind: KubeadmControlPlane\n    name: capi-control-plane\n    namespace: …
```

[VCDA-3152] Add additional properties to RDE

---

api/v1alpha4/vcdcluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml
controllers/cluster_scripts/cloud_init_control_plane.yaml
controllers/cluster_scripts/cloud_init_node.yaml
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
main.go
pkg/vcdclient/client.go
pkg/vcdclient/common_system_test.go
pkg/vcdclient/gateway.go

* moved VApp creation logic to vcdcluster_controller.go
* renamed vcdCluster.Status.RDEId to vcdCluster.Status.InfraId
* Fetch CAPVCD version automatically from release/version
@sahithi @ltimothy7 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/22)

[VCDA-3180, VCDA-3190, VCDA-3175] Code refactors and fetch CAPVCD version automatically

---

Makefile
controllers/cluster_scripts/cloud_init_control_plane.yaml
controllers/cluster_scripts/cloud_init_node.yaml
controllers/vcdcluster_controller.go
main.go
pkg/vcdclient/gateway.go

* Remove the retries in checkIfVSNotPending function. Make reconciliation retry the check
* Increase the worker controller threads to 10
* Remove lines to force systemd in cloud init scripts.
Testing done:
* Removed all the VS and checked if the cluster is waiting for VS to come up before attempting creation of a machine
@arunmk @ltimothy7 @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/26)

[VCDA-3198, VCDA-3199] Check if VS not pending to retry with reconciliation and worker controller thread increase

---

controllers/vcdcluster_controller.go
examples/capi-quickstart.yaml

- log messages should use key-value pairs and not string formatting
- fix examples/capi-quickstart.yaml - remove cgroup-driver parameter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/27)

Fix log messages and example input

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go

VCDMachine and VCDCluster should not wait for cluster creation events in deletion paths
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/34)

VCDA-3245: Clean cleanup of objects

---

controllers/vcdmachine_controller.go

If there is a disk attached, we need to wait until the CSI controller detaches it so that VCD does not put disks in an inconsistent state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/41)

VCDA-3267: wait for CPI to detach disks before shutting down node

---

controllers/cluster_scripts/cloud_init_control_plane.yaml
controllers/vcdmachine_controller.go
pkg/config/cloudconfig.go
pkg/vcdclient/auth_system_test.go

Testing done:
TKGm 1.3.0 ova: no antrea in tkr -> uses 0.11.3 antrea default
1.4.0 -> uses 0.11.3 antrea in tkr
1.4.1 -> uses 0.13.3 in tkr
Can specify cni and override tkr version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/57)

[VCDA-3238] Use antrea version in tkr bom

---

README.md
config/manager/kustomization.yaml
docs/MANAGEMENT_CLUSTER.md
examples/capi-quickstart.yaml

* Change git clone command to clone from 0.5.0 tag
* Change github link to https
* Update the clustectl version supported to 0.4.7
* Add comments suggesting users to use `system/administrator` over `administrator@system` when the user is system administrator
* Update CAPI version to v1alpha4 in README
* Add a table in README similar to what we have in CPI with link to 0.5.0 CAPVCD release tag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/58)

[VCDA-3358] Doc improvements

---

pkg/config/cloudconfig.go

* Currently when only the refresh token is specified, userOrg will be left empty and hence the call to get access token from refresh token will faill
* Fix: populate userOrg details in the config when username is not specified
* Refresh token login was broken since the changes to make use of GoVCD for token related operation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/60)

Populate config with userorg when username is not specified

---

controllers/vcdcluster_controller.go
pkg/vcdtypes/types.go
schema/schema_1_1_0.json

* Create a new capvcd schema file (1.1.0) and include only capi yaml in the spec
* Changes to remove update to any other field other than capi.yaml from the RDE spec
@sahithi @ltimothy7 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/65)

[VCDA-3385] Update CAPVCD RDE with only CAPI yaml

---

controllers/vcdcluster_controller.go
pkg/vcdtypes/types.go
schema/schema_1_1_0.json
vendor/modules.txt

* Add private section for kubeconfig in entity.status
* Fetch kubeconfig for the cluster and populate it in vcdcluster_controller.go
* Tested by creating a cluster and checked if kubeconfig section is getting populated.
* Used the kubeconfig in the status section to access the created cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/67)

[VCDA-3349 ]Add admin kubeconfig to entity.status

---

examples/rde1_1_0.json
schema/WIP_schema_1_1_0.json

This changeset has the work in progress schema file for RDE 1.1.0 and also an associated example instance.
Once the Go types have been created in the code, then we can delete the existing rde 1.1.0 schema and rename the newly introduced json file to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/77)

New RDE schema 1.1.0 and an associated example

---

controllers/vcdcluster_controller.go
pkg/config/cloudconfig.go

* Handled trailing '/' to avoid broken API paths.
* Done testing on CAPVCD cluster on personal testbed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/85)

[VCDA 3514] fix trailing '/' issue

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go

Problem: Controllers were using the Org with which CAPVCD is configured to place the cluster instead of the org the user belongs to.
Fix: Always use the user org to create the workload cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/88)

Always use the userorg to create the workload cluster

---

api/v1alpha4/zz_generated.conversion.go
api/v1beta1/vcdcluster_types.go
api/v1beta1/vcdmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachinetemplates.yaml
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go

ticket: VCDA-3453
* Changed compute policy to sizing policy in v1beta1 objects
* re-created the crds and updated conversion functions
Testing done:
* create a cluster using v1beta1
* Create a cluster using v1alpha4 and upgrade to v1beta1 (TODO)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/89)

Rename compute policy to sizing policy in v1beta1

---

api/v1alpha4/zz_generated.conversion.go
api/v1beta1/vcdcluster_types.go
api/v1beta1/vcdmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachinetemplates.yaml
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go

ticket: VCDA-3453
* Rename property computePolicy to sizingPolicy in VCDMachineSpec
* Use conversion-gen to re-generate conversion code
Testing:
* create cluster in v1beta1
* create cluster in v1alpha4 and upgrade hub version to v1beta1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/91)

Rename ComputePolicy property in VCDMachineSpec to SizingPolicy

---

controllers/vcdcluster_controller.go

* Only populate RDE.Spec.CapiYaml if is it initially empty, otherwise don't update it
* Testing Done:
- Created brand new cluster from VKP branch -> Observed RDE.Spec.CapiYaml gets populated with initial spec -> update capi yaml specs -> RDE.Spec.CapiYaml doesn't get overridden as it isn't empty
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/112)

[VCDA-3469] - Stop updating RDE.Spec.CapiYaml if not empty - VKP branch

---

controllers/vcdcluster_controller.go

* Only populate RDE.Spec.CapiYaml if is it initially empty, otherwise don't update it
* Testing Done:
- Created brand new cluster -> RDE.Spec.CapiYaml gets populated with initial spec -> update capi yaml specs -> RDE.Spec.CapiYaml doesn't get updated as it is no longer empty
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/105)

VCDA-3469: Update RDE.Spec.CapiYaml only if empty

---

pkg/vcdclient/auth.go
pkg/vcdclient/auth_system_test.go
pkg/vcdclient/client.go
pkg/vcdclient/common_system_test.go
testdata/auth_test.yaml
testdata/config_test.yaml
testdata/vcd_info.yaml

* when authenticating using refresh token, follow the following steps
* authenticate as a system org user
* if the above step fails, authenticate as a tenant user
* this PR also fixes authentication based tests which were broken
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/119)

[VCDA-3475] Fix refresh token issue with system admin when username is not provided

---

pkg/config/cloudconfig.go
pkg/vcdclient/client.go

* Publicized config helper function to re-use in client
* Pass in `system/administrator` as `userOrg: system`, `username: administrator` to AuthConfig instead of passing entire string
* Testing done:
- Successfully created and deleted cluster with SysAdmin CAPVCD credentials, and `system/administrator` in capi.yaml
- Successfully created and deleted cluster with SysAdmin CAPVCD credentials, and tenant user in capi.yaml
- Successfully created and deleted cluster with tenant admin CAPVCD credentials, and tenant user in capi.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/117)

[VCDA-3603] Fix sysadmin cluster creation

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
pkg/vcdclient/vapp.go

* During delete cluster operation, delete the vApp if and only if vApp has the ```InfraId``` as metadata property.
* Created a generic validation function in vApp.go to check whether a key-value pair is matched in vApp's metadata.
* Test Done:
1. If vAppmetadataUpdated is true, deletion process will be in stuck.
2. In current version, vAppmetadataUpdate will not be reset until the deletion process is done.
3. If InfraId is mismatched, deletion process will be in stuck and customers could see error hint in logs.
* To summarize, customers have choice to keep any component they want (vApp, VMs, load balance components).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provi …

[VCDA-3533] Delete the vApp if and only if rdeId (matches) present in the vApp

---

api/v1beta1/vcdcluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml
controllers/vcdcluster_controller.go

We were using the Update earlier which is fine for the Status() field and nobody else updates it at this point. We did not use Patch since there was an admission controller on Ready that failed.
~In this PR we trick the admission controller and provide the Ready also in the differential, and update what we need with the right `Ready` value.~
Edit: Later trials indicated that there was no use of this hack. I will commit this for now. If someone finds the issue again, we have a fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/138)

VCDA-3661: Move from Update to Patch while updating the field status.infraId.

---

controllers/vcdmachine_controller.go
go.mod
go.sum
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/util/defined_entity_util.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/util/set.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/util/util.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
vendor/modules.txt

occur if there is a failure in VM creation. The lbpool needs to be
created before the vm is powered on because the network route needs
to be ready.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/148)

VCDA-3713: keep control-plane IP list without repetitions. This could

---

config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml
controllers/vcdcluster_controller.go
infrastructure-vcd/v1.0.0/infrastructure-components.yaml
pkg/capisdk/defined_entity.go

* Status update will overwrite the default value.
* Set `vcdCluster.status.rdeInUse` to `1.1.0` before the status update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/157)

CAPVCD cluster creation bug because of `vcdCluster.Status.RdeInUse` key

---

controllers/capi_objects_utils.go
controllers/vcdcluster_controller.go
pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go

* Populate "entity.status.capvcd.capiStatusYaml"
* Testing done:
* Created a cluster and verified if capiStatusYaml is getting populated.
* Sample RDE:
```
{
"entity": {
...
"status": {
...
"capvcd": {
"capiStatusYaml": "apiversion: cluster.x-k8s.io/v1beta1\nkind: Cluster\nmetadata:\n  name: cluster12\n  namespace: default\nstatus:\n  conditions:\n  - lasttransitiontime: \"2022-06-02T16:01:45Z\"\n    message: \"\"\n    reason: \"\"\n    severity: \"\"\n    status: \"True\"\n    type: Ready\n  - lasttransitiontime: \"2022-06-02T16:01:45Z\"\n    message: \"\"\n    reason: \"\"\n    severity: \"\"\n    status: \"True\"\n    type: ControlPlaneInitialized\n  - lasttransitiontime: \"2022-06-02T16:01:45Z\"\n    message: \"\"\n    reason: \"\"\n    severity: \"\"\n    status: \"True\"\n    type: …
```

[VCDA-3801] Add capiStatusYaml to capvcdStatus

---

controllers/capi_objects_utils.go
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go
schema/WIP_schema_1_1_0.json

* Add node pool with the following details - sizingPolicy, placementPolicy, nvidiaGpu (not populated), replicas, DiskSizeMb, and node status
* Approach -
* 1. get all machine deployments using the cluster label and namespace
* 2. use the machine deployments to fetch vcdmachine template
* 3. use the machine deployment label, cluster label and namespace to query all machines
* 4. populate all node pools info for all machine deployment (uses info from vcdmachine template and machines)
for control plane machines
1. get all kcp objects using the cluster label and namespace
2. use the kcp object to get vcdmachine template object
3. use cluster label and kcp namespace to retrieve all the machines associated with the kcp
4. populate node pools for control plane objects - (uses information from …

[VCDA-3811] Create node pool with details from kubernetes objects

---

controllers/vcdcluster_controller.go

* Make sure every time an vApp is created, the metadata of vApp would be updated as well.
* Passed the testing: created new cluster -> delete vApp manually -> delete the whole cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/167)

[Bug Fix] Set VAppMetadataUpdated false if we need to create new vApp

---

config/crd/kustomization.yaml

This will enable move out of the box for VCD infra objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/173)

VCDA-3865: Add move annotation to vcd infra objects

---

controllers/cluster_scripts/cloud_init.tmpl
controllers/vcdmachine_controller.go

resolves https://github.com/vmware/cluster-api-provider-cloud-director/issues/171
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/172)

[VCDA-3860] correctly pull credentials from client auth config struct instead of cluster object

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
pkg/capisdk/defined_entity.go

* Bug fix for empty clusterID in capvcdrdeManager
* Add metadata (InfraId) into the vApp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/176)

[Bug fix] for empty clusterID in capvcdrdeManager

---

tanzu/crs/v1.4.2/v1.4.2-antrea.yaml.template
tanzu/crs/v1.4.2/v1.4.2.yaml.template
tanzu/crs/v1.5.4/v1.5.4-antrea.yaml.template
tanzu/crs/v1.5.4/v1.5.4.yaml.template

This brings in CRS templates for 1.5.4 and 1.4.2. The antrea yaml needs to be installed on the parent cluster (KinD) and the other yaml is to be installed on the child cluster itself. After some time, a `tanzu package installed list -A` will show the packages installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/182)

VCDA-3752, 3753, 3855, 3871 : CRS for TKGm v1.5.4 and v1.4.2

---

schema/WIP_schema_1_1_0.json
schema/schema_1_1_0.json

1. Pushed the image - [harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:vkp-branch](http://harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:vkp-branch)? NA
2. Are there API changes? - No If yes, please fill in the below
3. Updated conversions? NA
4. Updated CRDs? - NA
5. Updated capiYaml Examples? - NA
6. Updated infrastructure-components.yaml? - NA
7. Updated VCD-KE with the latest CAPVCD library? - NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/187)

[Bug fix] ClusterAPI status is array of strings, but should be array of objects

---

controllers/vcdcluster_controller.go
go.mod
go.sum
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
vendor/modules.txt

* Update common core library
* Make use of the updated GetLoadBalancer() to get the resource allocation list.
* Previously, if CAPVCD was upgraded, loadbalancer resources was not getting added to the vcdResourceSet in RDE. This was because there was no definite way to get the list of resources allocated when the load balancer is already present
* The updated `GetLoadBalancer()` method returns resources allocated as an additional return parameter. This helps to solves the use case of adding the existing
Pushed the image - [harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:vkp-branch](http://harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:vkp-branch)? yes
Are there API changes? - No
Updated conversions? NA
Updated CRDs? - NA
Updated capiYaml Examples? - NA …

[VCDA-3759] add resource allocatoin list to vcd resource set after upgrade

---

config/rbac/role.yaml
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
infrastructure-vcd/v1.0.0/infrastructure-components.yaml

- Add missing rbac kubebuilder codes in `vcdclustercontroller.go`.
- Update role.yaml and infrastructure-components.yaml
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/199)

[VCDA-3974] Add missing rbac kubebuilder codes in vcdclustercontroller.go

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go

Parameterize CPI/CSI versions similar to main. Also use `vkp` as version
- 
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/197)

VCDA-3983: point to vkp branch of CSI/CPI from CAPVCD:vkp

---

go.mod
go.sum
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
vendor/modules.txt

- Update CPI dependencies after regressions code change fix for VCDA-4026, VCDA-4025, VCDA-4015 from July 8th. 
- Commit reference: https://github.com/vmware/cloud-provider-for-cloud-director/commit/a03d0d9e871f8129e780de455e50de23bedbfb71
Fixes #
--- …

[VCDA-4029] Update common core dependencies for CAPVCD

---

controllers/vcdmachine_controller.go

-  Updated logging information to show the VM info if exists other than just a pointer.
- Separate conditions and logs for future root causes and understandings
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/209)

[VCDA-4059] Update Log VM details when network address check fails

---

controllers/capi_objects_utils.go
pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go

- Create and populate storage profile for node pools in capvcd status
- populate nvidiaGpu flag from vcdmachine template
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/210)

[VCDA-4050] Populate nvidiaGpu and storage profile for node pools

---

controllers/vcdcluster_controller.go

- 
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/212)

VCDA-4136 update rde with default storage class options in reconcileRDE

---

pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go

- Since errorSet and eventSet were missing from CAPVCD status definition, PatchRDE can reset the errors and events array in CAPVCD
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/215)

[VCDA-4052] Add errorSet and eventSet to CAPVCD status so PatchRDE() doesn't erase it

---

controllers/capi_objects_utils.go

- Storage profile was missing from the RDE section in control plane nodepools while worker nodepools showed correctly
- Populated nvidiaGPU field for future use cases in control plane machine
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-pr …

[VCDA-4150] Update missing storage profile, nvidia GPU field from control plane nodepools in RDE

---

controllers/vcdcluster_controller.go

- Get the entity type version of the RDE only if it doesn't have NO_RDE prefix
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/221)

Add check for no rde before getting the RDE entity type version

---

controllers/cluster_scripts/cloud_init.tmpl

- Fixes the issue of incorrect password for remote console logins on upon creation
- The second part of the fix is done via UI plugin (ssh login)
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/227)

[VCDA-4187] Fix for remote console logins in newly created VMs

---

api/v1alpha4/vcdcluster_conversion.go
api/v1alpha4/zz_generated.conversion.go
api/v1beta1/vcdcluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml
controllers/vcdcluster_controller.go
examples/capi-quickstart.yaml
infrastructure-vcd/v1.0.0/infrastructure-components.yaml

- Add executeWithoutRDE flag to VCDCluster. Which when set to true will instruct CAPVCD not to create RDEs for the cluster.
- Populate vcdCluster.Spec.RDEID so that clusterctl move when NO_RDE_ id is autogenerated also copies the ID in the vcdCluster spec. (There is an existing issue that clusterctl move does not copy the values in the status to the target cluster)
Testing done:
- Create cluster (NO_RDE)
- Resize cluster (NO_RDE)
- Clusterctl move (NO_RDE)
- Delete cluster (NO_RDE)
- Create cluster
- Resize cluster
- Clusterctl move
- Delete cluster  …

[VCDA-3896] Add executeWithoutRDE flag and populate rde id in spec

---

controllers/vcdcluster_controller.go
examples/rde1_1_0.json
pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go
schema/schema_1_1_0.json

- Add created by CAPVCD version to the schema.
- code changes to add created by version
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/229)

[VCDA-4198] Add capvcd created by version to capvcd RDE

---

controllers/cluster_scripts/cloud_init.tmpl
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
docs/MANAGEMENT_CLUSTER.md

- This removes installation of CPI, CSI and default storage-class in Kubernetes. The unnecessary phases and variables are also cleaned up.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/228)

VCDA-3853,3854: Remove install of CPI, CSI and default storage-class from CAPVCD

---

controllers/capi_objects_utils.go
controllers/cluster_scripts/cloud_init.tmpl
controllers/vcdmachine_controller.go

- Adds VCD_SITE_ID, CLUSTER_ID, TKG_VERSION, MACHINE_TYPE, MGMT fields to VM's created by CAPVCD. 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/226)

[VCDA-4086] Add metadata/extraConfig values for metering

---

controllers/cluster_scripts/cloud_init.tmpl

- Fixes the issue where reboot would generate new ssh host causing users to delete known_hosts in order to re-ssh into the machines
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/233)

[VCDA-4199] Fix SSH host keys delete per reboot

---

controllers/cluster_scripts/cloud_init.tmpl

- The check for vcloud-basic-auth.yaml file was still present though the file was removed.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/238)

VCDA-4273: Stop looking for vcloud-basic-auth.yaml

---

api/v1alpha4/vcdcluster_conversion.go

- If CAPVCD RDE ID has a NO_RDE_ prefix, the RDEVersion in use should be set to NO_RDE_ when upgrading CAPVCD.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/239)

changes to logic for RDE version in use during CAPVCD upgrade

---

controllers/capi_objects_utils.go
controllers/vcdcluster_controller.go
examples/rde1_1_0.json
go.mod
pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go
schema/schema_1_1_0.json

- Change schema and controller code to add entity.status.upgrade containing current and previous kubernetes versions and tkg versions
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/253)

[VCDA-4379] Add tkgVersion and kubernetes version as part of capvcd.upgrade in RDE

---

controllers/vcdcluster_controller.go
examples/rde1_1_0.json
infrastructure-vcd/v1.0.0/infrastructure-components.yaml
pkg/capisdk/defined_entity.go
pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go
schema/schema_1_1_0.json

- Make org and vdc an array in vcdProperties
- update external ID of the RDE
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/251)

[VCDA-4355] Update VcdProperties

---

Makefile
config/manager/manager.yaml.template
infrastructure-vcd/v1.0.0/infrastructure-components.yaml

- Add git sha to the deployment spec (config/manager/manager.yaml)
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/255)

[VCDA-4330]Add git sha to the images and deployment spec

---

controllers/cluster_scripts/cloud_init.tmpl
controllers/vcdmachine_controller.go

- Updated script to mark nodes with 'kubeadm join' and control plane labels as control plane machine type for metering
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/252)

[VCDA-4373] Update joined control plane nodes to be marked as control plane for metering

---

config/manager/manager.yaml
infrastructure-vcd/v1.0.0/infrastructure-components.yaml
schema/schema_1_1_0.json

- Schema for vcdOrg should be changed from an object to an array
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/258)

[VCDA-4413] Change vcdOrg in vcdProperties to an array in the schema

---

config/manager/manager.yaml
controllers/vcdcluster_controller.go
examples/rde1_1_0.json
infrastructure-vcd/v1.0.0/infrastructure-components.yaml
pkg/capisdk/defined_entity.go
pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go
schema/schema_1_1_0.json

- Make org and vdc in metadata as arrays
- update patchObj to handle nil values
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/261)

[VCDA-4414] Make org and vdc in metadata as arrays

---

controllers/vcdcluster_controller.go
infrastructure-vcd/v1.0.0/infrastructure-components.yaml
pkg/capisdk/defined_entity.go

- Update createdBy capvcd version before the first update to the capvcd RDE
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/256)

[VCDA-4369] Update createdBby version only when capvcd status is misisng

---

controllers/vcdcluster_controller.go
examples/rde1_1_0.json
pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go
schema/schema_1_1_0.json

…roperties
- Rename entity.status.capvcd.vcdOrg -> entity.status.capvcd.organizations
- Rename entity.status.capvcd.orgVdc -> entitty.status.capvcd.orgVdcs
- include ovdcNetworkName in entity.status.orgVdcs
- Revert metadata chages (to have arrays for org and vdc)
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

[VCDA-4429] Revert metadata changes and add ovdc network for the vdc list in vcdProperties

---

pkg/vcdtypes/rde_type_1_1_0/types_1_1_0.go

…ode pool definition
- if availableReplicas / desiredReplicas are 0, the json created to update the node pools will have missing keys for availableReplicas / desiredReplicas.
- omitempty in the RDE type definition should be removed in the node pools definition.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

[VCDA-4484] remove omitempty for integer fields in nodePool type definition

---

schema/schema_1_1_0.json

- Correct schema to reflect the code
- move ovdcNetworkName under orgVdc section in the schema
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/273)

[VCDA-4507] Correct schema to move ovdcNetworkName under orgVdc section

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
pkg/capisdk/defined_entity.go

- Update event set in vcdcluster_controller only when cluster.status.phase is not "Provisioned"
- Update event set in vcdmachine_controller only when machine.status.bootstrapready is false
Fixes #
- - - …

[VCDA-4514] Add events only on create operations

---

controllers/cluster_scripts/cloud_init.tmpl
controllers/vcdmachine_controller.go

- Remove cloud init lines where kubeadm join token is being generated as it is not used anywhere in the code.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/280)

[VCDA-4477] Remove lines generating a kubeadm token in the cloud init script

---

tanzu/crs/v1.4.3/v1.4.3.yaml.template
tanzu/crs/v1.5.4/v1.5.4.yaml.template

- Set the type of Cluster as Workload so that TMC allows it to be attached. The relevant code of interest in TMC is https://gitlab.eng.vmware.com/olympus/extension-framework/-/blob/master/pkg/clustermetadata/metadata.go#L268
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-clou …

VCDA-4559: Set cluster type to workload to attach to TMC

---

pkg/capisdk/defined_entity.go

-  Clean up spammed etag logging statements in CAPVCD
- Increase the verbosity of logging level
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/282)

[VCDA-4481] CAPVCD logs are spammed with "wrong etag" statements

---

config/manager/manager.yaml
templates/infrastructure-components.yaml

Refresh image up to commit: 89ca65f 
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/296)

[VCDA-4369]: Update image tag for consuming common core in CAPVCD

---

controllers/vcdcluster_controller.go
go.mod
go.sum
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/api_certificate_library_modified.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdswaggerclient/vcdconstants.go
vendor/modules.txt

Bump cloud provider version to fix the issue with duplicate network validation
- Bump cloud provider version to fix the issue with duplicate network validation
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/300)

fix: bump cloud provider version

---

go.mod
go.sum
vendor/modules.txt

- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/298)

[VCDA-4660] Refresh common core from main in CAPVCD main using hash 8574691ef708

---

templates/crs/cpi/cloud-director-ccm.yaml

- Previous merge of CPI CRS files was not latest as it was missing CLUSTER_ID env. 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/306)

[VCDA-4558][Fix] Update to the correct CPI CRS file content from CPI repo

---

controllers/vcdcluster_controller.go

…n status only if it is empty
- Update the function validateDerivedRDEProperties() to only verify the RDE version in use if VCD cluster status is empty.
- Tested locally by creating a cluster with CAPVCD_SKIP_RDE environment variable set
Fixes # https://github.com/vmware/cluster-api-provider-cloud-director/issues/309
- - - …

[VCDA-4713] Fix cluster creation with CAPVCD_SKIP_RDE set to true

---

controllers/vcdmachine_controller.go

- make attempt to add network to the VM is network connection section for the VM is missing.
- Tested by creating multiple node pools, resizing up one node pool and resizing down one node pool simultaneously.
Fixes #
- - - …

[VCDA-4679] Attempt adding network to the VM if it is missing

---

controllers/vcdcluster_controller.go

- When load balancer creation fails, error needs to be captured and reconciliation should error out.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/317)

[VCDA-4717] Handle error when load balancer creation fails (#312)

---

controllers/vcdmachine_controller.go

- Attempt adding network to the VM if it is missing
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/316)

[VCDA-4679] Attempt adding network to the VM if it is missing (#310)

---

templates/cluster-template-v1.20.8-crs.yaml
templates/cluster-template-v1.20.8.yaml
templates/cluster-template-v1.21.8-crs.yaml
templates/cluster-template-v1.21.8.yaml
templates/cluster-template-v1.22.9-crs.yaml
templates/cluster-template-v1.22.9.yaml
templates/cluster-template.yaml

- Fix clusterctl templates so that they can be used directly
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/319)

[VCDA-4741] Use double quotes for username, password and refresh token variables in templates

---

go.mod
main.go

- Update timestamp from UNIX to GMT format
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/324)

[VCDA-4734] Change log timestamps from UNIX to GMT formatting

---

go.mod
main.go

- Change log timestamps from UNIX to GMT format in CAPVCD
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/325)

[VCDA-4734] Change log timestamps from UNIX to GMT format (#324)

---

api/v1alpha4/vcdmachine_conversion.go

- providerID should be set when CRDs are converted from v1alpha4 to v1beta1
- If it is not set, machine reconciler will fail repeatedly.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/327)

[VCDA-4755] set vcdmachine.status.providerID when converting objects from v1alpha4 to v1beta1

---

api/v1alpha4/vcdmachine_conversion.go

- vcdmachine conversion logic should set vcdmachine.status.providerID = vcdmachine.spec.providerID
- Fixes clusterctl upgrade operation
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/331)

[VCDA-4773] When converting from v1alpha4 to v1beta1, make sure to set provider ID in vcdMachine status (#327)

---

controllers/vcdmachine_controller.go

- the code to redact the cloud init file is not necessary anymore.
- Redaction was needed when the cloud init script had authentication information for CPI and CSI.
- currently capvcd uses CRS to install CPI and CSI and they are installed separately
- So, Redacting the cloud init script is not needed
Fixes #
- - - …

[VCDA-4757] Remove code to redact the cloud init script as redaction logic is not necessary anymore

---

controllers/capi_objects_utils.go
controllers/vcdcluster_controller.go
templates/clusterctl.yaml

- Ready flag should not be set when the cluster is being resized
- Check if all the machines created are at the same version as expected to set the ready flag
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud- …

[VCDA-4743] Iterate all machines to compute ready flag

---

controllers/capi_objects_utils.go
controllers/vcdcluster_controller.go
templates/clusterctl.yaml

- the code to redact the cloud init file is not necessary anymore.
- Redaction was needed when the cloud init script had authentication information for CPI and CSI.
- currently capvcd uses CRS to install CPI and CSI and they are installed separately
- So, Redacting the cloud init script is not needed
Fixes #
- - - …

[VCDA-4743] Iterate all machines to compute ready flag (#330)

---

controllers/cluster_scripts/cloud_init.tmpl

- pass `--now` switch to `systemctl enable` to start the service immediately
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/341)

VCDA-4777 modify enablement/starting of metering.service

---

controllers/cluster_scripts/cloud_init.tmpl

(cherry picked from commit 6d1a7d6b69c623952f874db52738fa7e3e37940a)
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/342)

VCDA-4777 modify enablement/starting of metering.service (#341)

---

templates/clusterctl.yaml

- set username and password as empty strings in clusterctl.yaml
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/343)

[VCDA-4786] set username and password as empty strings in clusterctl.yaml

---

templates/clusterctl.yaml

(cherry picked from commit f046f0042a33e11bc19fbf076fa85c8a3052a644)
- set username and password as empty strings in clusterctl.yaml 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/344)

[VCDA-4786] set username and password as empty strings in clusterctl.yaml (#343)

---

controllers/vcdcluster_controller.go

- Fixes the issue where RDE ID is missing from VCDCluster spec after clusterctl move for a cluster with no RDE
- Update spec.rdeId with the infra ID
- Tested clusterctl move for a cluster with no RDE
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/354)

[VCDA-4900] Fix clusterctl move issues because of missing RDE ID in spec

---

api/v1beta1/vcdmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachinetemplates.yaml
controllers/vcdmachine_controller.go

Fixes https://github.com/vmware/cluster-api-provider-cloud-director/issues/235
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/254)

Support multiple NIC for machines

---

controllers/vcdmachine_controller.go

#254 erroneously re-introduced the import of `io/ioutil`, which had been removed previously. Go complains about it, because it is not used since 73b198a, rendering the code base uncompilable.
This commit fixes that, and it is able to compile again.
n/a, I could open one, if needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/361)

Remove redundant import, making the code base compilable again

---

api/v1alpha4/vcdcluster_conversion.go
api/v1alpha4/vcdmachine_conversion.go
api/v1alpha4/vcdmachinetemplate_conversion.go

- Add conversion logic to restore newly created fields using data annotation.
Fixes # https://github.com/vmware/cluster-api-provider-cloud-director/issues/355
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/367)

[CAFV-81] Modify conversion logic to restore v1beta1 fields using data annotation

---

controllers/vcdmachine_controller.go
pkg/capisdk/defined_entity.go

- Added an event HealthCheckFailedEvent
- Will be added to the RDE when Health Check for a machine in the cluster fails.
- Tested with and without MHC enabled
Sample event from the UI:
Fixes #
- - - …

[CAFV-130] add health check failed event to RDE when MHC fails

---

controllers/vcdmachine_controller.go
pkg/capisdk/defined_entity.go

- Node unhealthiness should be posted as an event to the RDE when CAPVCD detects that the node is unhealthy
- NodeUnhealthy event should NOT be generated when the node is being provisioned.
Fixes #
- - - …

[CAFV-158] Add node unhealthy event to the RDE

---

docs/WIRE_LOGS.md

- Fix commands to enable / disable wire logs in CAPVCD pods.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/384)

[CAFV-166] Fix wire log commands in the doc

---

README.md

(cherry picked from commit ea515ac2ac425246515b7f389ffd9fb143f0982b)
- Reverse the release order of the tables in README.md
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/386)

[CAFV-142] Reverse the release order of the tables in README.md (#385)

---

controllers/vcdcluster_controller.go
go.mod
go.sum
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
vendor/modules.txt

- sync with CPI common-core (a1a149d80f32) for "Add Ovdc check when getting ovdc network"
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/399)

[CAFV-171] [common-core] sync with CPI common-core (a1a149d80f32) for "Add Ovdc check when getting ovdc network"

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
pkg/capisdk/defined_entity.go
pkg/util/defined_entity_utils.go

-  Ensure CAPVCD Controller accepts RDE 1.1.0 for cluster creation
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/402)

[CAFV-177] Ensure CAPVCD Controller accepts RDE 1.1.0 for cluster creation

---

controllers/capi_objects_utils.go

-  make RDE type version consistent
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/403)

Testfest-2-27] RDE 1.2 usage by Nodepools in CAPVCD

---

api/v1beta2/vcdmachine_types.go
controllers/vcdmachine_controller.go

- Add omitempty to extraOvdcNetworks field to ensure null doesn't get used when field is empty
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/405)

[CAFV-181] Testfest - Add omitempty for extraOvdcNetworks to avoid null when empty

---

examples/capi-quickstart.yaml

- I tried to use the example workload resource file to create manifest for a cluster by updating the values in the example file but it failed due to invalid names in some of the objects. 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/314)

fix: fields in example resources

---

config/certmanager/certificate.yaml
config/default/manager_webhook_patch.yaml
templates/infrastructure-components.yaml

This MR updates the webhook server cert secret name from `webhook-server-cert` to `capvcd-webhook-server-cert` to avoid other controllers Certificate overwriting the CAPVCD certificate. `webhook-server-cert` is very common name and it is default secret name of any operator created using kubebuilder.
This is a problem when multiple controller built using kubebuilder are deployed in the namespace.
- 
Fixes #
- - - …

fix: update webhook server secret name

---

api/v1beta2/zz_generated.deepcopy.go

Adds missing changes in #405
```
go build -ldflags "-X github.com/vmware/cluster-api-provider-cloud-director/version.Version=main-branch" -o /build/vcloud/cluster-api-provider-cloud-director main.go
api/v1beta2/zz_generated.deepcopy.go:372:8: cannot use new([]string) (type *[]string) as type []string in assignment
api/v1beta2/zz_generated.deepcopy.go:373:6: invalid indirect of *in (type []string)
api/v1beta2/zz_generated.deepcopy.go:375:4: invalid indirect of out (type []string)
api/v1beta2/zz_generated.deepcopy.go:375:30: invalid indirect of in (type []string)
api/v1beta2/zz_generated.deepcopy.go:376:9: invalid indirect of out (type []string)
api/v1beta2/zz_generated.deep copy.go:376:15: invalid indirect of in (type []string
```
1. …

Fix deepy copy for in.ExtraOvdcNetworks

---

schema/schema_1_1_0.json

Updates the capvcdCluster schema apiVersion to 1.1
- 
- [x ] updated any relevant dependencies
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/413)

[CAFV-195] Updates the capvcdCluster schema apiVersion to 1.1

---

examples/capi-quickstart.yaml
templates/cluster-class-template.yaml
templates/cluster-template-v1.20.8-crs.yaml
templates/cluster-template-v1.20.8.yaml
templates/cluster-template-v1.21.8-crs.yaml
templates/cluster-template-v1.21.8.yaml
templates/cluster-template-v1.22.9-crs.yaml
templates/cluster-template-v1.22.9.yaml
templates/cluster-template-v1.23.10-crs.yaml
templates/cluster-template-v1.23.10.yaml
templates/cluster-template.yaml

- update v1beta2 capvcd objects in template files and example files
- Only examine the capvcd object API version.
- Will validate all the template files during E2E testing
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/417)

[CAFV-159] update v1beta2 capvcd objects in template files and example files

---

go.mod
go.sum
vendor/modules.txt

- Updates common core commit to use the one from CPI 1.4.z branch
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/420)

[CAFV-208] Update CAPVCD 1.1.z common core to use CPI 1.4.z common core

---

artifacts/bom.json.template
artifacts/dependencies.txt.template
config/manager/manager.yaml.template

Update manifests generated to point to projects.registry.vmware.com
- Update manifests generated to point to projects.registry.vmware.com/vmware-cloud-director
- Since `clusterctl init` can override which repository to pull from, we can ensure that all of our manifests will point to a reachable location (projects.registry.vmware.com)
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

[CAFV-200] Update manifests generated to point to projects.registry.vmware.com

---

controllers/cluster_scripts/cloud_init.tmpl
controllers/vcdmachine_controller.go

- PostCustomization phases are a bit complicated now. They have to be ordered in cloud_init and `phases` arrays. Removing phases conditionally is easier than adding. 
- Now, `NvidiaRuntimeInstall` is not applied for the first CP node but there is no such restriction in the VCDMachine level. This PR adds `NvidiaRuntimeInstall` regardless of `useControlPlaneScript`.
- Now, the proxy configuration for containerd is rendered in cloud_init.tmpl regardless of their content. `/etc/systemd/system/containerd.service.d/http-proxy.conf` should be rendered only when `HttpProxy` or `HttpsProxy` has a value.  This will allow users to use their own proxy settings for containerd without using built-in features. 
2. Updated …

Improve post customization phases

---

templates/clusterctl.yaml

- Update clusterctl.yaml file to use v1.0.1 as the Provider URL/folder path
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/437)

[CAFV-226] Update Provider url path to use v1.0.1 folder path in clusterctl.yaml

---

go.mod
go.sum
vendor/modules.txt

-  [common-core] sync with CPI common-core for the latest testing common code - remove PVC related k8s functions
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/436)

[CAFV-223] [common-core] sync with CPI common-core for the latest testing common code - remove PVC related k8s functions

---

controllers/cluster_scripts/cloud_init.tmpl

BootstrapRunCmd generated from CAPI is a compound command. The BootstrapRunCmd will be of the following format
```
kubeadm join --config /run/kubeadm/kubeadm-join-config.yaml  && echo success > /run/cluster-api/bootstrap-success.complete
```
`trap` cannot be used to catch the error if the executed command is part of an && or ||
> The ERR trap is not executed if the failed command is part of the command list immediately following a [while](https://ss64.com/bash/while.html) or until keyword, part of the test in an if statement, part of a && or || list, or if the command's return value is being inverted via !.
These are the same conditions obeyed by the errexit option.
This PR uses stderr redirection to catch the …

[CAFV-77] Update cloud init script to read kubeadm failure reason

---

Dockerfile
Dockerfile-ConversionGen
Makefile
go.mod
go.sum

- Upgrade golang version to 1.19
- go mod edit -go=1.19
- go mod tidy
- go mod vendor
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/440)

[CAFV-246] upgrade go version to 1.19

---

templates/crs/tanzu/v1.6.1/v1.6.1.yaml.template

This is a cherry-pick of [CAFV-182] Remove unneeded config values and management label (#408) from `main` branch
----
* removed vsphere and management references and other unneded values
* reverted antrea
* removed oidc, nsxt, and tkg values
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/447)

[CAFV-256] Port `workload` cluster label to `1.0.z` branch

---

Makefile
config/manager/manager.yaml
config/manager/manager.yaml.template
templates/infrastructure-components.yaml

- Use projects-stg as internal registry
- [NA] updated any relevant documentation or examples
NA
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/449)

CAFV-261: Use projects-stg as build registry

---

README.md
config/manager/manager.yaml
docs/UPGRADES.md
templates/infrastructure-components.yaml

- Update documentation for patching CAPVCD image to 1.0.2
- Update image to point to public harbor for CAPVCD 1.0.2
- Update interop matrix table for K8s version and CAPVCD 1.0.2
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/452)

[CAFV-270] Image and documentation update for CAPVCD 1.0.2

---

templates/clusterctl.yaml

- Update clusterctl.yaml file with v1.0.2 folder path from v1.0.1
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/453)

[CAFV-270] Update clusterctl.yaml with proper paths for CAPVCD 1.0.2

---

controllers/vcdcluster_controller.go
pkg/capisdk/defined_entity.go

- Skip RDE upgrades if VCDKECluster is True
- Standalone capvcd cluster - RDE upgrades should happen and status updates must happen.
- VCD-KE cluster - RDE upgrades should not happen and but status updates must happen
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-direc …

Skip RDE upgrades if VCDKECluster is True

---

Dockerfile
Makefile

Multiple fixes to move from a photon base to a scratch image.
- fix image layers to prevent unneeded layer. By moving the `chmod +x` to before the copy, we don't have to include that layer in the changes
```bash
vcloud2          latest            32186ae3133f   35 minutes ago   93.8MB
vcloud           latest            af43cf4b9444   35 minutes ago   151MB
```
If we inspect the layers we can see the copy layer is 57MB and the chmod layer is also 57MB because it has to modify the permissions on that binary in the docker layer.
```bash
57 MB  COPY /build/vcloud/cluster-api-provider-cloud-director . # buildkit
57 MB  RUN /bin/sh -c chmod +x /opt/vcloud/bin/cluster-api-provider-cloud-director # buildkit
```
after …

Image updates to reduce image size, move to golang static binary and scratch image

---

controllers/vcdcluster_controller.go

- get all CAPVCD clusters based on major version during `cluster delete`.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/460)

[CAFV-277] Ensure the CAPVCD cluster can be deleted successfully

---

Makefile
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
main.go
pkg/capisdk/defined_entity.go
release/release.go
release/version.go

- Change version to be in line with other components, so that the git-sha is also embedded in it
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/465)

CAFV-281: Use same version methodology as other components

---

api/v1alpha4/vcdcluster_conversion.go
api/v1alpha4/vcdmachine_conversion.go
api/v1beta1/vcdmachine_conversion.go

- Restore parameters which are not restored in conversion logic
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/463)

[CAFV-269] Restore missing paramters in conversion logic

---

docs/CLUSTERCTL.md

- Update `CLUSTERCTL.MD` with instruction for setting up v1.1.0
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/464)

[CAFV-279] Update CLUSTERCTL docs to use 1.1.0

---

tests/e2e/doc.md
tests/e2e/e2e_suite_test.go
tests/e2e/setup_kind_cluster.sh
tests/e2e/utils/cluster_util.go
tests/e2e/utils/config_map_files/vcloud-ccm-config.yaml
tests/e2e/utils/config_map_files/vcloud-csi-config.yaml
tests/e2e/utils/k8s_util.go
tests/e2e/utils/node_pool_scaling_utils.go
tests/e2e/utils/utils.go
tests/e2e/workload_cluster_test.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/capiyaml_utils.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/client.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/rde_utils.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/set_utils.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/vcd_utils.go
vendor/modules.txt

- Use `Server Side Apply` to apply and delete objects of `capiYaml`.
- Update the instruction documents for `CAPVCD` test automation.
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/467)

[CAFV-285] Refractor CAPVCD test automation AND use server side apply to do Kubernetes operations

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go

- Close idle http connections after reconciliation
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/468)

[CAFV-286] close idle http connections when reconciliation ends

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go

(cherry picked from commit 5be8096fb84e6bc201849beb7978fb96231e6dad)
- Close idle http connections after reconciliation
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/472)

[cherry-pick][CAFV-286] close idle http connections when reconciliation ends

---

templates/cluster-template-v1.24.10-crs.yaml
templates/cluster-template-v1.24.10.yaml
templates/cluster-template-v1.25.7-crs.yaml
templates/cluster-template-v1.25.7.yaml

-  add clusterctl templates for 1.24 and 1.25 versions
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/476)

[CAFV-290] add clusterctl templates for 1.24 and 1.25 versions

---

templates/cluster-template-v1.24.10-crs.yaml
templates/cluster-template-v1.24.10.yaml
templates/cluster-template-v1.25.7-crs.yaml
templates/cluster-template-v1.25.7.yaml

(cherry picked from commit 0ed458a60a92302e28710ebb2983a9986484188a)
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/478)

[CAFV-290] add clusterctl templates for 1.24 and 1.25 versions (#476)

---

Makefile

- Downgrade kustomize to 4.5.7, controller-gen to 0.4.1
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/490)

[CAFV-298] Downgrade kustomize to 4.5.7, controller-gen 0.4.1

---

Makefile

* Downgrade kustomize to 4.5.7, controller-gen 0.4.1
* Address Adnan CR: Use constant for kustomize version
---------
(cherry picked from commit 81031e51818863fef435252d4185cdda83e26e0e)
- Cherrypick commit 81031e5 from main to 1.1.z
Fixes #
- - - …

[CAFV-298] Cherrypick commit 81031e5: Downgrade kustomize to 4.5.7, controller-gen 0.4.1 (#490)

---

controllers/vcdmachine_controller.go

Currently, it always dumps cloud-init scripts, which makes logs of operator dirty. Also, cloud-init script contain sensitive data coming from kubeadmconfig. For example, join tokens, files to mount node via k8s secrets etc.
It is enough to set -zap-log-level=2 to print cloud-init scripts to logs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/484)

Log cloud-init scripts only for debug mode

---

go.mod
go.sum
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/k8sclient.go
vendor/modules.txt

- Update common core sync with CPI main commit e8d9efd
- Main purpose of this sync is to increase test automation timeouts
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/501)

[CAFV-303] Update common core sync with CPI main commit e8d9efd

---

config/manager/manager.yaml
config/manager/manager.yaml.template
templates/infrastructure-components.yaml

- Remove fields which are not covered by PSP
- runAsGroup
- fsGroup
- changed done as per https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/#eliminate-non-standard-options
Fixes #311
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/503)

[CAFV-235] Remove fields as per PodSecurityPolicy deprecation and removal from Kubernetes

---

examples/capi-quickstart.yaml
templates/cluster-class-template.yaml
templates/cluster-template-v1.20.8-crs.yaml
templates/cluster-template-v1.20.8.yaml
templates/cluster-template-v1.21.8-crs.yaml
templates/cluster-template-v1.21.8.yaml
templates/cluster-template-v1.22.9-crs.yaml
templates/cluster-template-v1.22.9.yaml
templates/cluster-template-v1.23.10-crs.yaml
templates/cluster-template-v1.23.10.yaml
templates/cluster-template-v1.24.10-crs.yaml
templates/cluster-template-v1.24.10.yaml
templates/cluster-template-v1.25.7-crs.yaml
templates/cluster-template-v1.25.7.yaml
templates/cluster-template.yaml

- disable host path provisioned for cluster templates
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/502)

disable host path provisioner for clusters

---

controllers/cluster_scripts/cloud_init.tmpl

- Usually `systemctl restart` will wait for a service to restart completely. However, there seem to be well-known issues with containerd which make the `systemctl restart containerd` to return before containerd is restarted in some rare cases. The fix here waits for containerd to start by looking at some properties of the runtime.
Tested by examining logs.
Fixes #CAFV-319
- - - …

CAFV-319: Properly wait for containerd to start completely.

---

artifacts/bom.json.template
artifacts/dependencies.txt.template

- Updates dependency.txt.template, bom.json.template to use `__REGISTRY__` placeholders
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/520)

[CAFV-325] Use placeholders for registry for dependencies.txt

---

controllers/cluster_scripts/cloud_init.tmpl

Wait for the RuntimeReady status using crictl to ensure that the containerd service is up.
(cherry picked from commit a441041cf8fb2a073ebcb9563007f1e6f172d1a0)
- Cherry-pick
Fixes #512
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/522)

CAFV-319: Properly wait for containerd to start completely. (#512)

---

controllers/cluster_scripts/cloud_init.tmpl
controllers/vcdmachine_controller.go

- Do not customize VM even if EnableNvidiaGPU is set up. The customization that we performed was (slightly) helping customers who would install GPU drivers in GPU nodes directly. However this interferes with the NVIDIA GPU operator functionality.
- Those customers who would install GPU drivers in GPU nodes directly will be impacted by this change. However they can include the customization into their workflow directly since it is a very small customization
- Note that the flag has not yet been deprecated. The next API update should begin to show the deprecation.
4. Updated …

CAFV-326: Make EnableNvidiaGPU into a no-op

---

controllers/cluster_scripts/cloud_init.tmpl
controllers/vcdmachine_controller.go

- Do not customize VM even if EnableNvidiaGPU is set up. The customization that we performed was (slightly) helping customers who would install GPU drivers in GPU nodes directly. However this interferes with the NVIDIA GPU operator functionality.
- Those customers who would install GPU drivers in GPU nodes directly will be impacted by this change. However they can include the customization into their workflow directly since it is a very small customization
- Note that the flag has not yet been deprecated. The next API update should begin to show the deprecation.
(cherry picked from commit a5ab47d2c6114a4d1885c7ea56ecaba1ce49e7ef)
- 
1. Updated …

CAFV-326: Make EnableNVidiaGPU into a no-op (#524)

---

.gitignore
Makefile

A recent PR (#466) split commands that were on the same line into multiple lines. Now, when `go test` runs, it does not have the environment variable required by envtest, and fails.
```console
> make test
bin/controller-gen crd rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
test -f bin/testbin/setup-envtest.sh || curl -sSLo bin/testbin/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.8.3/hack/setup-envtest.sh
source bin/testbin/setup-envtest.sh
fetch_envtest_tools bin/testbin
bash: line 1: fetch_envtest_tools: command not found
make: *** [Makefile:133: test] Error 127
```
The same PR introduced the use of a relative path for …

Fix the `test` make target, and make it possible to test a subset of packages

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go

… errorSet
- VCD has a bug where update to errorSet, eventSet or vcdResourceSet may fail. This PR ensures that RDE updates won't stop cluster creation/deletion.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/537)

[CAFV-332] Changes to avoid failure during update to vcdResourceSet, eventSet or errorSet

---

controllers/cluster_scripts/cloud_init.tmpl

- In TKG 2.3.0, remote console is not enabled by default, for which we need to enable ssh password based login. This was taken care by the PR https://github.com/vmware/cluster-api-provider-cloud-director/pull/535
- However, for ssh password based login to be allowed in TKG 2.3.0, UsePAM variable in sshd_config should also be commented out. This PR removes UsePAM variable from /etc/ssh/sshd_config to allow ssh password based root login for TKG 2.3.0
If applicable, …

[CAFV-346]: comment out UsePAM variable before ssh restart in cloud init

---

controllers/cluster_scripts/cloud_init.tmpl

- SSH password based login was needed for TKG 2.3.0 since remote console login was disabled by default
- Since CSE won't support TKG 2.3.0 and only TKG 2.3.1 is supported, this change is not needed anymore
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/547)

remove changes to sshd_config for password based ssh

---

templates/cluster-template-v1.24.17-tkgv2.3.1-crs.yaml
templates/cluster-template-v1.24.17-tkgv2.3.1.yaml
templates/cluster-template-v1.25.13-tkgv2.3.1-crs.yaml
templates/cluster-template-v1.25.13-tkgv2.3.1.yaml
templates/cluster-template-v1.25.13-tkgv2.4.0-crs.yaml
templates/cluster-template-v1.25.13-tkgv2.4.0.yaml
templates/cluster-template-v1.26.8-tkgv2.3.1-crs.yaml
templates/cluster-template-v1.26.8-tkgv2.3.1.yaml
templates/cluster-template-v1.26.8-tkgv2.4.0-crs.yaml
templates/cluster-template-v1.26.8-tkgv2.4.0.yaml
templates/cluster-template-v1.27.5-tkgv2.4.0-crs.yaml
templates/cluster-template-v1.27.5-tkgv2.4.0.yaml

- Add clusterctl templates for TKG 2.3.1 and TKG 2.4.0
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/546)

[CAFV-327] Add clusterctl templates for TKG 2.3.1 and TKG 2.4.0 

---

config/manager/manager.yaml
templates/crs/cpi/cloud-director-ccm.yaml
templates/crs/csi/csi-controller-crs.yaml
templates/crs/csi/csi-node-crs.yaml
templates/infrastructure-components.yaml

CSI, CAPVCD of the 4.2 stack
- Update manifests to point to the right versions of CPI, CSI, CAPVCD of the 4.2 stack
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/549)

CAFV-377: Update manifests to point to the right versions of CPI,

---

controllers/vcdcluster_controller.go
docs/UPGRADES.md

This is solely to fix this small typo:
https://github.com/vmware/cluster-api-provider-cloud-director/issues/540
Just a typo (`verison`) in the error message when there was an invalid RDE version
The other is just a docs fix when I searched for verison
- 
https://github.com/vmware/cluster-api-provider-cloud-director/issues/540
Fixes #
https://github.com/vmware/cluster-api-provider-cloud-director/issues/540
- - - …

fix: small version typo in an error message

---

controllers/vcdcluster_controller.go
docs/UPGRADES.md

(cherry picked from commit 46734c9fc9967945d2fc2b10876881e5c6364c75)
This is solely to fix this small typo:
https://github.com/vmware/cluster-api-provider-cloud-director/issues/540
Just a typo (`verison`) in the error message when there was an invalid RDE version
The other is just a docs fix when I searched for verison
https://github.com/vmware/cluster-api-provider-cloud-director/issues/540
Fixes #
https://github.com/vmware/cluster-api-provider-cloud-director/issues/540
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

fix: small version typo in an error message (#541)

---

controllers/vcdcluster_controller.go
pkg/capisdk/defined_entity.go

Remove the RdeAvailable event which is not serving any meaningful purpose. RDE has become defacto way.
This was added in the beginning of CAPVCD, but doesn't add any value compared to 100 other important things capvcd does today.
- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provi …

[CAFV-387] Remove redundant RdeAvailable events

---

controllers/vcdcluster_controller.go
pkg/capisdk/defined_entity.go

…pose. (#556)
This was added in the beginning of CAPVCD, but doesn't add any value compared to 100 other important things capvcd does.
(cherry picked from commit b54607e820cc10cc69c912e4ae560ab302701809)
- 
Fixes #
- - - …

[CAFV-387][Cherrypick]Remove the redundant RDEAvailable event

---

controllers/vcdmachine_controller.go

for badly created VMs
- Sometimes VMs are not created correctly. So using the `vm.VM.Name` can cause panics. Changing it to `machine.Name` in one observed instance. However there needs to be a complete scan of code and a more intrusive fix later.
Fixes #
- - - …

CAFV-392: Use machine.Name so that vm.VM.name will not cause panics

---

controllers/vcdmachine_controller.go

MachineDeployment stores the cluster.Name (jose-test-2) in the "cluster.x-k8s.io/cluster-name" label instead of vcdcluster.Name (jose-test-2-grxh6) so this PR fixes this issue to prevent machine from being created
Error
```
ERROR	unable to get vApp name from cluster name [%s], machine [%s]	{"controller": "vcdmachine", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "VCDMachine", "VCDMachine": {"name":"j","namespace":"capi-system"}, "namespace": "capi-system", "name": "", "reconcileID": "", "cluster": "", "ovdc": "", "machine": "", "clusterName": "", "OVDC ID": "", "error": "unable to get MachineDeployment name from cluster [jose-test-2-grxh6], machine []: [unable to find machine deployment for cluster [], machine []]"
```
- 
If yes, please …

fix: an issue when get MachineDeployment

---

controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
main.go

- Reduce sync time of the controllers to 2 mins so that the vcdcluster controller gets called more frequently
- In vcdmachine_controller, perform login only if necessary.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/577)

[CAFV-411] decrease sync time in main.go to 2 minutes

---

artifacts/bom.json.template
artifacts/dependencies.txt.template

- Updates dependencies.txt.template to use 'vmware-cloud-director/cluster-api-provider-cloud-director' as part of image path for consistency
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/578)

[VCDA-6992] Update dependencies.txt.template to use vmware-cloud-director for image path

---

controllers/vcdcluster_controller.go

- Verified that CAPVCD is not affected by OVDC rename
- Fixed a possible nil pointer dereference when OVDC is renamed
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/588)

[CAFV-399] fix a possible nil pointer dereference

---

controllers/vcdcluster_controller.go

-  code fix for customer bug - [Capvcd RDE status storing VDC name instead of ID]
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/603)

[CAFV-434] code fix for customer bug - [Capvcd RDE status storing VDC name instead of ID]

---

api/v1alpha4/vcdmachine_conversion.go
api/v1beta1/vcdmachine_conversion.go
api/v1beta3/vcdcluster_types.go
api/v1beta3/vcdmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclustertemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdmachinetemplates.yaml
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
templates/infrastructure-components.yaml

- Updates vApp name in the case of a multi-AZ cluster to include node pool name and OVDC ID
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/593)

[CAFV-362] Update vapp naming for multizone

---

templates/cluster-template-v1.26.11-tkgv2.5.0-crs.yaml
templates/cluster-template-v1.26.11-tkgv2.5.0.yaml
templates/cluster-template-v1.27.8-tkgv2.5.0-crs.yaml
templates/cluster-template-v1.27.8-tkgv2.5.0.yaml
templates/cluster-template-v1.28.4-tkgv2.5.0-crs.yaml
templates/cluster-template-v1.28.4-tkgv2.5.0.yaml

TKG 2.5 templates for clusterctl
- 
- [ X] No
- [X ] No
- [ X] No
- [ X] No
NA
Fixes #
NA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/606)

[VCDA-7218] TKG 2.5 templates for clusterctl

---

Makefile
go.mod
go.sum

- upgrade go version to v1.21
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/608)

[CAFV-439]upgrade go version to v1.21

---

controllers/cluster_scripts/ignition_network_init_script.tmpl
controllers/vcdmachine_controller.go
examples/flatcar-ignition.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-v1.24.10-crs-ignition.yaml
templates/cluster-template-v1.24.10-ignition.yaml
templates/cluster-template-v1.25.7-crs-ignition.yaml
templates/cluster-template-v1.25.7-ignition.yaml
templates/clusterctl.yaml

This PR adds support for Flatcar as a base OS which relies on ignition (as opposed to cloud-init).
What it does:
1. The bootstrap format must be set to `ignition` in `KubeadmControlPlane|KubeadmConfig.spec.format` (as opposed to `cloud-config`) as seen [there](https://github.com/vmware/cluster-api-provider-cloud-director/pull/581/files#diff-745dc72aa3794c5a7a2cf1ac8496ca99a0a6a08a7312b4ea3370db0412ecf7eeR240).
1. Then the data for the ignition must be set under `KubeadmControlPlane|KubeadmConfig.spec.ignition.containerLinuxConfig.additionalConfig`. More information about the specifications of ignition can be found in the [Flatcar doc](https://www.flatcar.org/docs/latest/provisioning/ignition/specification/). …

Add support for ignition (Flatcar OS)

---

docs/CLUSTERCTL.md

- add 1.3.z and 1.2.z to table
- updated core capi compatibility to v1.5.4 for 1.3.z and main
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/614)

[CAFV-449][1.3.z] update CLUSTERCTL.md with updated versions

---

docs/CLUSTERCTL.md

- add  1.2.z  to table
- updated core capi compatibility to v1.5.4 for main and v1.4.0 for 1.2.z
- removed Setup section
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/615)

[CAFV-449][1.2.z]update CLUSTERCTL.md with updated versions

---

docs/CLUSTERCTL.md

- added 1.3.z and 1.2.z to Core CAPI compatability table
- update main core capi version to v1.5.4
- mark Setup as applicable only for 1.1.z and earlier.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/617)

[CAFV-449][main]update CLUSTERCTL.md with updated versions

---

controllers/vcdmachine_controller.go

- Ensure that VM is in RESOLVED state or beyond, before attaching network. If not, the network may get attached improperly (there will be no network access), leading to VMs running cloud-init with no network attached.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-direc …

CAFV-374: ensure that VM is RESOLVED before adding networks

---

controllers/vcdcluster_controller.go

- There was a regression which was introduced in the single-zone fix. This clears up teh regression and allows non-AZ clusters to be created again. 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/630)

CAFV-364: fix issues with non-AZ clusters

---

docs/CRS.md

- 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/635)

[CAFV-466][main] CRS.md examples should copy CRS files to $HOME

---

docs/CLUSTERCTL.md
docs/CRS.md

- use relevant CRS versions in CLUSTERCTL.md
- CRS.md examples tell users they can use custom path
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/633)

[CAFV-466][1.3.z] bring CLUSTERCTL.md and CRS.md up to date

---

api/v1beta3/vcdcluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vcdclustertemplates.yaml
controllers/capi_objects_utils.go
controllers/vcdcluster_controller.go
controllers/vcdmachine_controller.go
go.mod
go.sum
pkg/capisdk/defined_entity.go
pkg/util/util.go
templates/infrastructure-components.yaml
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/client.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/testingsdk/vcd_utils.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/client.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/org.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/vapp.go
vendor/modules.txt

- This allows both OVDC URN ID (`urn:vcloud:vdc:<uuid>`) and OVDC name to be used in cluster creation.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/639)

CAFV-444: Allow ovdc name and ID to both be used by clients

---

templates/cluster-template-v1.20.8-crs.yaml
templates/cluster-template-v1.24.10-crs.yaml
templates/cluster-template-v1.24.17-tkgv2.3.1-crs.yaml
templates/cluster-template-v1.25.13-tkgv2.3.1-crs.yaml
templates/cluster-template-v1.25.13-tkgv2.4.0-crs.yaml
templates/cluster-template-v1.25.7-crs.yaml
templates/cluster-template-v1.26.11-tkgv2.5.0-crs.yaml
templates/cluster-template-v1.26.8-tkgv2.3.1-crs.yaml
templates/cluster-template-v1.26.8-tkgv2.4.0-crs.yaml
templates/cluster-template-v1.27.5-tkgv2.4.0-crs.yaml
templates/cluster-template-v1.27.8-tkgv2.5.0-crs.yaml
templates/cluster-template-v1.28.4-tkgv2.5.0-crs.yaml
templates/clusterctl.yaml

Add these labels to all crs template files:
```
cluster-role.tkg.tanzu.vmware.com/management: ""
tanzuKubernetesRelease: ${TARGET_TANZUKUBERNETESRELEASE}
tkg.tanzu.vmware.com/cluster-name: ${CLUSTER_NAME}
```
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/638)

[CAFV-464][1.3.z]Add suggested CRS labels to crs.yaml files

---

go.mod
go.sum
pkg/util/util.go
vendor/github.com/vmware/cloud-provider-for-cloud-director/pkg/vcdsdk/gateway.go
vendor/modules.txt

- The OVDC in a dcgroup network is nil.
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/640)

CAFV-475: Handle null OVDCs in dcgroup OVDC network lookup

---

controllers/vcdcluster_controller.go

- CAPVCD fails to delete all the vApps
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/642)

[CAFV-478] CAPVCD fails to delete all the vApps

---

templates/crs/csi/csi-controller-crs.yaml
templates/crs/csi/csi-node-crs.yaml

- CSI manifests are not updated for CSI-1.6.0 which brings in volume expansion and block support. This change updates the manifests to have the same RBAC and support containers that are present in the CSI 1.6.0 release.
Fixes #650 
Fixes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cluster-api-provid …

650: Fix issue with CSI manifests for v1.6.0
